version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./mvnw dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: cd account && ./mvnw clean integration-test 

      # save test report
      - store_test_results:
          path: account-service/target/surefire-reports

      # send test report to CodeCov
      - run:
          name: Send report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)