version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # run tests!
      - run: cd account && ./mvnw clean integration-test 

      # save test report
      - store_test_results:
          path: account/account-service/target/surefire-reports

      # send test report to CodeCov
      - run:
          name: Send report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
