spring:
  application:
    name: account-service
  config:
    import: 'optional:configserver:'
  datasource:
    url: jdbc:h2:mem:accountDB
    driverClassName: org.h2.Driver
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect